### ISSUE TITLE
Is there a way to include a standard `figure` environment when required?

### ISSUE THREAD

**Issue by slochower** [scotthartley/pandoc-chemfig#1]
Is there an easy way to specify that I just want a standard `figure` environment and not a `wrapfloat` environment? I ask this because if I have a figure that's the full width of the page, and I specify `wwidth=0 wpos=c`, I get text "trying" to wrap around the figure. 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/5393995/45121328-a413f100-b115-11e8-9c07-5c7c6160a45f.png">

(In this case, actually, there is another problem, which is that the figure is actually larger than `\textwidth` and I'd like to specify that, but I understand that's not possible at the moment.)

**Comment by scotthartley** [comment]
You should be able to just leave out the wwidth/wpos attributes entirely. LaTeX formats should then process them without using wrapfloat at all.

**Comment by slochower** [comment]
Hmm. I can confirm that leaving out `wwidth` and `wpos` gives a `figure` environment. But, if I remove those commands, for some reason I get a hard-coded `\textbf{???}` for the figure reference in the text. That is, after the `()` for the image, I have just`{#fig:test}` and in the text I'm using `@fig:text` for reference. I can see the hard-coded question marks by capturing the output of Pandoc with `-s` while compiling the PDF. Is it possible that `pandoc-chemfig` somehow interferes with regular figure referencing?

**Comment by slochower** [comment]
Oh! My fault. This was a dumb mistake. When I leave out `wwidth` and `wpos`, turning a wrapped environment into a regular `figure`, I need to include `pandoc-fignos` to get the right referencing. Sorry 'bout that. Closing issue.
